train epoch:1:   0%|                                                                                                                                                                  | 0/20227 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "traineval.py", line 45, in <module>
    if cfg.w_wandb:
  File "traineval.py", line 24, in train_val
    trainer.epoch(epoch + 1)
  File "/home/datassd/yilin/Codes/Hand/ConditionHOI/epochbase.py", line 237, in epoch
    self.one_batch(sample)
  File "/home/datassd/yilin/Codes/Hand/ConditionHOI/epochbase.py", line 190, in one_batch
    outputs = self.model_forward(data_elements)
  File "/home/datassd/yilin/Codes/Hand/ConditionHOI/epochbase.py", line 90, in model_forward
    feats, SD_maps = self.ConditionNet(obj_vs, rhand_vs, region) # cSDF_maps = [pred_map_obj, pred_map_obj_masked]
  File "/home/yilin/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/datassd/yilin/Codes/Hand/ConditionHOI/models/ConditionNet.py", line 66, in forward
    feat_om, trans3, trans_feat3 = self.obj_masked_encoder(obj_masked_pc)
  File "/home/yilin/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/datassd/yilin/Codes/Hand/ConditionHOI/models/pointnet_encoder.py", line 148, in forward
    return torch.cat([x, pointfeat], 1), trans, trans_feat
RuntimeError: CUDA out of memory. Tried to allocate 200.00 MiB (GPU 0; 10.76 GiB total capacity; 2.29 GiB already allocated; 119.31 MiB free; 2.39 GiB reserved in total by PyTorch)